#格式  道具内部ID:显示名称:购买价格(金锭)
#format  Props internal ID:display name:purchase price (gold ingot)
#道具内部id请参考 https://github.com/lt-name/MurderMystery_Nukkit/wiki/Item-ID
items:
  - 21:神秘药水:1
  - 22:护盾生成器:2
  - 23:减速雪球:1