name: Java CI

on:
  push:
    branches: [ master, PM1E ]
  pull_request:
    branches: [ master, PM1E ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.1
        with:
          maven-version: 3.6.3
      - name: Build projects
        run: mvn -B package
      - run: mkdir staging && cp target/*.jar staging
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: MurderMystery-SNAPSHOT
          path: staging
